package net.nemerosa.versioning

import groovy.transform.Canonical

/**
 * Version information generated by the plug-in.
 */
@Canonical
class VersionInfo {

    String scm
    String display
    String full
    String branch
    String build
    String source
    String sourcetype
    String commit

}
