package net.nemerosa.versioning.core;

/**
 * Version information generated by the plug-in.
 */
public class VersionInfo {

    public static final VersionInfo NONE = new VersionInfo(
            "n/a",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
    );

    private final String scm;
    private final String branch;
    private final String branchType;
    private final String branchId;
    private final String commit;
    private final String display;
    private final String full;
    private final String base;
    private final String build;

    public VersionInfo(String scm, String branch, String branchType, String branchId, String commit, String display, String full, String base, String build) {
        this.scm = scm;
        this.branch = branch;
        this.branchType = branchType;
        this.branchId = branchId;
        this.commit = commit;
        this.display = display;
        this.full = full;
        this.base = base;
        this.build = build;
    }

    public String getScm() {
        return scm;
    }

    public String getBranch() {
        return branch;
    }

    public String getBranchType() {
        return branchType;
    }

    public String getBranchId() {
        return branchId;
    }

    public String getCommit() {
        return commit;
    }

    public String getDisplay() {
        return display;
    }

    public String getFull() {
        return full;
    }

    public String getBase() {
        return base;
    }

    public String getBuild() {
        return build;
    }
}
